[package]
name = "tealdeer"
version = "0.2.0"
authors = ["Danilo Bargen <mail@dbrgn.ch>"]
repository = "https://github.com/dbrgn/tealdeer/"
homepage = "https://github.com/dbrgn/tealdeer/"
license = "MIT/Apache-2.0"
readme = "README.md"
description = "Fetch and show tldr help pages for many CLI commands. Full featured offline client with caching support."

[[bin]]
name = "tldr"
path = "src/main.rs"

[features]
logging = ["env_logger"]
dev = ["clippy"]

[dependencies]
log = "^0.3"
curl = "^0.2"
docopt = "^0.6"
walkdir = "^0.1"
ansi_term = "^0.7"
rustc-serialize = "^0.3"
clippy = {version = "~0.0.37", optional = true}
env_logger = { version = "^0.3", optional = true }

[dev-dependencies]
tempdir = "^0.3"
